//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lopus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукт
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукт()
        {
            this.Материал = new HashSet<Материал>();
        }
    
        public int ID { get; set; }
        public string Наименование { get; set; }
        public string Артикул { get; set; }
        public Nullable<decimal> Мин_стоим { get; set; }
        public byte[] Изображение { get; set; }
        public string Тип_прод { get; set; }
        public Nullable<int> Кол_во_для_пр { get; set; }
        public Nullable<int> Ном_цех { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Материал> Материал { get; set; }
    }
}
